/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimoniesRouteImport } from './routes/testimonies'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShareTestimonyRouteImport } from './routes/share-testimony'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as PrayerRequestRouteImport } from './routes/prayer-request'
import { Route as PodcastsRouteImport } from './routes/podcasts'
import { Route as PlanAVisitRouteImport } from './routes/plan-a-visit'
import { Route as MediaRouteImport } from './routes/media'
import { Route as GiveRouteImport } from './routes/give'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookAppointmentRouteImport } from './routes/book-appointment'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SermonsIndexRouteImport } from './routes/sermons.index'
import { Route as PodcastsIndexRouteImport } from './routes/podcasts.index'
import { Route as MinistriesIndexRouteImport } from './routes/ministries.index'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SermonsSlugRouteImport } from './routes/sermons.$slug'
import { Route as PodcastsSlugRouteImport } from './routes/podcasts.$slug'
import { Route as MinistriesWomensFellowshipRouteImport } from './routes/ministries.womens-fellowship'
import { Route as MinistriesMensFellowshipRouteImport } from './routes/ministries.mens-fellowship'
import { Route as MinistriesSlugRouteImport } from './routes/ministries.$slug'
import { Route as MediaPodcastRouteImport } from './routes/media.podcast'
import { Route as MediaGalleryRouteImport } from './routes/media.gallery'
import { Route as EventsCouplesRetreatRouteImport } from './routes/events.couples-retreat'
import { Route as EventsCouplesRouteImport } from './routes/events.couples'
import { Route as AdminVisitsRouteImport } from './routes/admin.visits'
import { Route as AdminTestimoniesRouteImport } from './routes/admin.testimonies'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSermonsRouteImport } from './routes/admin.sermons'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminPrayerRouteImport } from './routes/admin.prayer'
import { Route as AdminPodcastsRouteImport } from './routes/admin.podcasts'
import { Route as AdminPastorsRouteImport } from './routes/admin.pastors'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminMinistriesRouteImport } from './routes/admin.ministries'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminGivingRouteImport } from './routes/admin.giving'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as ApiPublicPingTestRouteImport } from './routes/api/public/ping-test'
import { Route as ApiPublicEnsureMediaBucketRouteImport } from './routes/api/public/ensure-media-bucket'

const TestimoniesRoute = TestimoniesRouteImport.update({
  id: '/testimonies',
  path: '/testimonies',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTestimonyRoute = ShareTestimonyRouteImport.update({
  id: '/share-testimony',
  path: '/share-testimony',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRequestRoute = PrayerRequestRouteImport.update({
  id: '/prayer-request',
  path: '/prayer-request',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsRoute = PodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanAVisitRoute = PlanAVisitRouteImport.update({
  id: '/plan-a-visit',
  path: '/plan-a-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAppointmentRoute = BookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsIndexRoute = SermonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SermonsRoute,
} as any)
const PodcastsIndexRoute = PodcastsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PodcastsRoute,
} as any)
const MinistriesIndexRoute = MinistriesIndexRouteImport.update({
  id: '/ministries/',
  path: '/ministries/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MediaRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SermonsSlugRoute = SermonsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SermonsRoute,
} as any)
const PodcastsSlugRoute = PodcastsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PodcastsRoute,
} as any)
const MinistriesWomensFellowshipRoute =
  MinistriesWomensFellowshipRouteImport.update({
    id: '/ministries/womens-fellowship',
    path: '/ministries/womens-fellowship',
    getParentRoute: () => rootRouteImport,
  } as any)
const MinistriesMensFellowshipRoute =
  MinistriesMensFellowshipRouteImport.update({
    id: '/ministries/mens-fellowship',
    path: '/ministries/mens-fellowship',
    getParentRoute: () => rootRouteImport,
  } as any)
const MinistriesSlugRoute = MinistriesSlugRouteImport.update({
  id: '/ministries/$slug',
  path: '/ministries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaPodcastRoute = MediaPodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => MediaRoute,
} as any)
const MediaGalleryRoute = MediaGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => MediaRoute,
} as any)
const EventsCouplesRetreatRoute = EventsCouplesRetreatRouteImport.update({
  id: '/couples-retreat',
  path: '/couples-retreat',
  getParentRoute: () => EventsRoute,
} as any)
const EventsCouplesRoute = EventsCouplesRouteImport.update({
  id: '/couples',
  path: '/couples',
  getParentRoute: () => EventsRoute,
} as any)
const AdminVisitsRoute = AdminVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimoniesRoute = AdminTestimoniesRouteImport.update({
  id: '/testimonies',
  path: '/testimonies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSermonsRoute = AdminSermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrayerRoute = AdminPrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPodcastsRoute = AdminPodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPastorsRoute = AdminPastorsRouteImport.update({
  id: '/pastors',
  path: '/pastors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMinistriesRoute = AdminMinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGivingRoute = AdminGivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPingTestRoute = ApiPublicPingTestRouteImport.update({
  id: '/api/public/ping-test',
  path: '/api/public/ping-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEnsureMediaBucketRoute =
  ApiPublicEnsureMediaBucketRouteImport.update({
    id: '/api/public/ensure-media-bucket',
    path: '/api/public/ensure-media-bucket',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/give': typeof GiveRoute
  '/media': typeof MediaRouteWithChildren
  '/plan-a-visit': typeof PlanAVisitRoute
  '/podcasts': typeof PodcastsRouteWithChildren
  '/prayer-request': typeof PrayerRequestRoute
  '/sermons': typeof SermonsRouteWithChildren
  '/share-testimony': typeof ShareTestimonyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonies': typeof TestimoniesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/giving': typeof AdminGivingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/ministries': typeof AdminMinistriesRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pastors': typeof AdminPastorsRoute
  '/admin/podcasts': typeof AdminPodcastsRoute
  '/admin/prayer': typeof AdminPrayerRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/sermons': typeof AdminSermonsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonies': typeof AdminTestimoniesRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/events/couples': typeof EventsCouplesRoute
  '/events/couples-retreat': typeof EventsCouplesRetreatRoute
  '/media/gallery': typeof MediaGalleryRoute
  '/media/podcast': typeof MediaPodcastRoute
  '/ministries/$slug': typeof MinistriesSlugRoute
  '/ministries/mens-fellowship': typeof MinistriesMensFellowshipRoute
  '/ministries/womens-fellowship': typeof MinistriesWomensFellowshipRoute
  '/podcasts/$slug': typeof PodcastsSlugRoute
  '/sermons/$slug': typeof SermonsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/media/': typeof MediaIndexRoute
  '/ministries/': typeof MinistriesIndexRoute
  '/podcasts/': typeof PodcastsIndexRoute
  '/sermons/': typeof SermonsIndexRoute
  '/api/public/ensure-media-bucket': typeof ApiPublicEnsureMediaBucketRoute
  '/api/public/ping-test': typeof ApiPublicPingTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/give': typeof GiveRoute
  '/plan-a-visit': typeof PlanAVisitRoute
  '/prayer-request': typeof PrayerRequestRoute
  '/share-testimony': typeof ShareTestimonyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonies': typeof TestimoniesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/giving': typeof AdminGivingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/ministries': typeof AdminMinistriesRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pastors': typeof AdminPastorsRoute
  '/admin/podcasts': typeof AdminPodcastsRoute
  '/admin/prayer': typeof AdminPrayerRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/sermons': typeof AdminSermonsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonies': typeof AdminTestimoniesRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/events/couples': typeof EventsCouplesRoute
  '/events/couples-retreat': typeof EventsCouplesRetreatRoute
  '/media/gallery': typeof MediaGalleryRoute
  '/media/podcast': typeof MediaPodcastRoute
  '/ministries/$slug': typeof MinistriesSlugRoute
  '/ministries/mens-fellowship': typeof MinistriesMensFellowshipRoute
  '/ministries/womens-fellowship': typeof MinistriesWomensFellowshipRoute
  '/podcasts/$slug': typeof PodcastsSlugRoute
  '/sermons/$slug': typeof SermonsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/media': typeof MediaIndexRoute
  '/ministries': typeof MinistriesIndexRoute
  '/podcasts': typeof PodcastsIndexRoute
  '/sermons': typeof SermonsIndexRoute
  '/api/public/ensure-media-bucket': typeof ApiPublicEnsureMediaBucketRoute
  '/api/public/ping-test': typeof ApiPublicPingTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/give': typeof GiveRoute
  '/media': typeof MediaRouteWithChildren
  '/plan-a-visit': typeof PlanAVisitRoute
  '/podcasts': typeof PodcastsRouteWithChildren
  '/prayer-request': typeof PrayerRequestRoute
  '/sermons': typeof SermonsRouteWithChildren
  '/share-testimony': typeof ShareTestimonyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonies': typeof TestimoniesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/giving': typeof AdminGivingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/ministries': typeof AdminMinistriesRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pastors': typeof AdminPastorsRoute
  '/admin/podcasts': typeof AdminPodcastsRoute
  '/admin/prayer': typeof AdminPrayerRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/sermons': typeof AdminSermonsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonies': typeof AdminTestimoniesRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/events/couples': typeof EventsCouplesRoute
  '/events/couples-retreat': typeof EventsCouplesRetreatRoute
  '/media/gallery': typeof MediaGalleryRoute
  '/media/podcast': typeof MediaPodcastRoute
  '/ministries/$slug': typeof MinistriesSlugRoute
  '/ministries/mens-fellowship': typeof MinistriesMensFellowshipRoute
  '/ministries/womens-fellowship': typeof MinistriesWomensFellowshipRoute
  '/podcasts/$slug': typeof PodcastsSlugRoute
  '/sermons/$slug': typeof SermonsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/media/': typeof MediaIndexRoute
  '/ministries/': typeof MinistriesIndexRoute
  '/podcasts/': typeof PodcastsIndexRoute
  '/sermons/': typeof SermonsIndexRoute
  '/api/public/ensure-media-bucket': typeof ApiPublicEnsureMediaBucketRoute
  '/api/public/ping-test': typeof ApiPublicPingTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/book-appointment'
    | '/contact'
    | '/events'
    | '/give'
    | '/media'
    | '/plan-a-visit'
    | '/podcasts'
    | '/prayer-request'
    | '/sermons'
    | '/share-testimony'
    | '/sitemap.xml'
    | '/testimonies'
    | '/admin/appointments'
    | '/admin/contact'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/giving'
    | '/admin/login'
    | '/admin/media'
    | '/admin/ministries'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/pastors'
    | '/admin/podcasts'
    | '/admin/prayer'
    | '/admin/registrations'
    | '/admin/sermons'
    | '/admin/settings'
    | '/admin/testimonies'
    | '/admin/visits'
    | '/events/couples'
    | '/events/couples-retreat'
    | '/media/gallery'
    | '/media/podcast'
    | '/ministries/$slug'
    | '/ministries/mens-fellowship'
    | '/ministries/womens-fellowship'
    | '/podcasts/$slug'
    | '/sermons/$slug'
    | '/admin/'
    | '/events/'
    | '/media/'
    | '/ministries/'
    | '/podcasts/'
    | '/sermons/'
    | '/api/public/ensure-media-bucket'
    | '/api/public/ping-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-appointment'
    | '/contact'
    | '/give'
    | '/plan-a-visit'
    | '/prayer-request'
    | '/share-testimony'
    | '/sitemap.xml'
    | '/testimonies'
    | '/admin/appointments'
    | '/admin/contact'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/giving'
    | '/admin/login'
    | '/admin/media'
    | '/admin/ministries'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/pastors'
    | '/admin/podcasts'
    | '/admin/prayer'
    | '/admin/registrations'
    | '/admin/sermons'
    | '/admin/settings'
    | '/admin/testimonies'
    | '/admin/visits'
    | '/events/couples'
    | '/events/couples-retreat'
    | '/media/gallery'
    | '/media/podcast'
    | '/ministries/$slug'
    | '/ministries/mens-fellowship'
    | '/ministries/womens-fellowship'
    | '/podcasts/$slug'
    | '/sermons/$slug'
    | '/admin'
    | '/events'
    | '/media'
    | '/ministries'
    | '/podcasts'
    | '/sermons'
    | '/api/public/ensure-media-bucket'
    | '/api/public/ping-test'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/book-appointment'
    | '/contact'
    | '/events'
    | '/give'
    | '/media'
    | '/plan-a-visit'
    | '/podcasts'
    | '/prayer-request'
    | '/sermons'
    | '/share-testimony'
    | '/sitemap.xml'
    | '/testimonies'
    | '/admin/appointments'
    | '/admin/contact'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/giving'
    | '/admin/login'
    | '/admin/media'
    | '/admin/ministries'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/pastors'
    | '/admin/podcasts'
    | '/admin/prayer'
    | '/admin/registrations'
    | '/admin/sermons'
    | '/admin/settings'
    | '/admin/testimonies'
    | '/admin/visits'
    | '/events/couples'
    | '/events/couples-retreat'
    | '/media/gallery'
    | '/media/podcast'
    | '/ministries/$slug'
    | '/ministries/mens-fellowship'
    | '/ministries/womens-fellowship'
    | '/podcasts/$slug'
    | '/sermons/$slug'
    | '/admin/'
    | '/events/'
    | '/media/'
    | '/ministries/'
    | '/podcasts/'
    | '/sermons/'
    | '/api/public/ensure-media-bucket'
    | '/api/public/ping-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookAppointmentRoute: typeof BookAppointmentRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  GiveRoute: typeof GiveRoute
  MediaRoute: typeof MediaRouteWithChildren
  PlanAVisitRoute: typeof PlanAVisitRoute
  PodcastsRoute: typeof PodcastsRouteWithChildren
  PrayerRequestRoute: typeof PrayerRequestRoute
  SermonsRoute: typeof SermonsRouteWithChildren
  ShareTestimonyRoute: typeof ShareTestimonyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimoniesRoute: typeof TestimoniesRoute
  MinistriesSlugRoute: typeof MinistriesSlugRoute
  MinistriesMensFellowshipRoute: typeof MinistriesMensFellowshipRoute
  MinistriesWomensFellowshipRoute: typeof MinistriesWomensFellowshipRoute
  MinistriesIndexRoute: typeof MinistriesIndexRoute
  ApiPublicEnsureMediaBucketRoute: typeof ApiPublicEnsureMediaBucketRoute
  ApiPublicPingTestRoute: typeof ApiPublicPingTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonies': {
      id: '/testimonies'
      path: '/testimonies'
      fullPath: '/testimonies'
      preLoaderRoute: typeof TestimoniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-testimony': {
      id: '/share-testimony'
      path: '/share-testimony'
      fullPath: '/share-testimony'
      preLoaderRoute: typeof ShareTestimonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-request': {
      id: '/prayer-request'
      path: '/prayer-request'
      fullPath: '/prayer-request'
      preLoaderRoute: typeof PrayerRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-a-visit': {
      id: '/plan-a-visit'
      path: '/plan-a-visit'
      fullPath: '/plan-a-visit'
      preLoaderRoute: typeof PlanAVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-appointment': {
      id: '/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof BookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons/': {
      id: '/sermons/'
      path: '/'
      fullPath: '/sermons/'
      preLoaderRoute: typeof SermonsIndexRouteImport
      parentRoute: typeof SermonsRoute
    }
    '/podcasts/': {
      id: '/podcasts/'
      path: '/'
      fullPath: '/podcasts/'
      preLoaderRoute: typeof PodcastsIndexRouteImport
      parentRoute: typeof PodcastsRoute
    }
    '/ministries/': {
      id: '/ministries/'
      path: '/ministries'
      fullPath: '/ministries/'
      preLoaderRoute: typeof MinistriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof MediaRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sermons/$slug': {
      id: '/sermons/$slug'
      path: '/$slug'
      fullPath: '/sermons/$slug'
      preLoaderRoute: typeof SermonsSlugRouteImport
      parentRoute: typeof SermonsRoute
    }
    '/podcasts/$slug': {
      id: '/podcasts/$slug'
      path: '/$slug'
      fullPath: '/podcasts/$slug'
      preLoaderRoute: typeof PodcastsSlugRouteImport
      parentRoute: typeof PodcastsRoute
    }
    '/ministries/womens-fellowship': {
      id: '/ministries/womens-fellowship'
      path: '/ministries/womens-fellowship'
      fullPath: '/ministries/womens-fellowship'
      preLoaderRoute: typeof MinistriesWomensFellowshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries/mens-fellowship': {
      id: '/ministries/mens-fellowship'
      path: '/ministries/mens-fellowship'
      fullPath: '/ministries/mens-fellowship'
      preLoaderRoute: typeof MinistriesMensFellowshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries/$slug': {
      id: '/ministries/$slug'
      path: '/ministries/$slug'
      fullPath: '/ministries/$slug'
      preLoaderRoute: typeof MinistriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/podcast': {
      id: '/media/podcast'
      path: '/podcast'
      fullPath: '/media/podcast'
      preLoaderRoute: typeof MediaPodcastRouteImport
      parentRoute: typeof MediaRoute
    }
    '/media/gallery': {
      id: '/media/gallery'
      path: '/gallery'
      fullPath: '/media/gallery'
      preLoaderRoute: typeof MediaGalleryRouteImport
      parentRoute: typeof MediaRoute
    }
    '/events/couples-retreat': {
      id: '/events/couples-retreat'
      path: '/couples-retreat'
      fullPath: '/events/couples-retreat'
      preLoaderRoute: typeof EventsCouplesRetreatRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/couples': {
      id: '/events/couples'
      path: '/couples'
      fullPath: '/events/couples'
      preLoaderRoute: typeof EventsCouplesRouteImport
      parentRoute: typeof EventsRoute
    }
    '/admin/visits': {
      id: '/admin/visits'
      path: '/visits'
      fullPath: '/admin/visits'
      preLoaderRoute: typeof AdminVisitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonies': {
      id: '/admin/testimonies'
      path: '/testimonies'
      fullPath: '/admin/testimonies'
      preLoaderRoute: typeof AdminTestimoniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sermons': {
      id: '/admin/sermons'
      path: '/sermons'
      fullPath: '/admin/sermons'
      preLoaderRoute: typeof AdminSermonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prayer': {
      id: '/admin/prayer'
      path: '/prayer'
      fullPath: '/admin/prayer'
      preLoaderRoute: typeof AdminPrayerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/podcasts': {
      id: '/admin/podcasts'
      path: '/podcasts'
      fullPath: '/admin/podcasts'
      preLoaderRoute: typeof AdminPodcastsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pastors': {
      id: '/admin/pastors'
      path: '/pastors'
      fullPath: '/admin/pastors'
      preLoaderRoute: typeof AdminPastorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ministries': {
      id: '/admin/ministries'
      path: '/ministries'
      fullPath: '/admin/ministries'
      preLoaderRoute: typeof AdminMinistriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/giving': {
      id: '/admin/giving'
      path: '/giving'
      fullPath: '/admin/giving'
      preLoaderRoute: typeof AdminGivingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/ping-test': {
      id: '/api/public/ping-test'
      path: '/api/public/ping-test'
      fullPath: '/api/public/ping-test'
      preLoaderRoute: typeof ApiPublicPingTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ensure-media-bucket': {
      id: '/api/public/ensure-media-bucket'
      path: '/api/public/ensure-media-bucket'
      fullPath: '/api/public/ensure-media-bucket'
      preLoaderRoute: typeof ApiPublicEnsureMediaBucketRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminGivingRoute: typeof AdminGivingRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMinistriesRoute: typeof AdminMinistriesRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPastorsRoute: typeof AdminPastorsRoute
  AdminPodcastsRoute: typeof AdminPodcastsRoute
  AdminPrayerRoute: typeof AdminPrayerRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminSermonsRoute: typeof AdminSermonsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimoniesRoute: typeof AdminTestimoniesRoute
  AdminVisitsRoute: typeof AdminVisitsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminContactRoute: AdminContactRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminGivingRoute: AdminGivingRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMinistriesRoute: AdminMinistriesRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPastorsRoute: AdminPastorsRoute,
  AdminPodcastsRoute: AdminPodcastsRoute,
  AdminPrayerRoute: AdminPrayerRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminSermonsRoute: AdminSermonsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimoniesRoute: AdminTestimoniesRoute,
  AdminVisitsRoute: AdminVisitsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsRouteChildren {
  EventsCouplesRoute: typeof EventsCouplesRoute
  EventsCouplesRetreatRoute: typeof EventsCouplesRetreatRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsCouplesRoute: EventsCouplesRoute,
  EventsCouplesRetreatRoute: EventsCouplesRetreatRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface MediaRouteChildren {
  MediaGalleryRoute: typeof MediaGalleryRoute
  MediaPodcastRoute: typeof MediaPodcastRoute
  MediaIndexRoute: typeof MediaIndexRoute
}

const MediaRouteChildren: MediaRouteChildren = {
  MediaGalleryRoute: MediaGalleryRoute,
  MediaPodcastRoute: MediaPodcastRoute,
  MediaIndexRoute: MediaIndexRoute,
}

const MediaRouteWithChildren = MediaRoute._addFileChildren(MediaRouteChildren)

interface PodcastsRouteChildren {
  PodcastsSlugRoute: typeof PodcastsSlugRoute
  PodcastsIndexRoute: typeof PodcastsIndexRoute
}

const PodcastsRouteChildren: PodcastsRouteChildren = {
  PodcastsSlugRoute: PodcastsSlugRoute,
  PodcastsIndexRoute: PodcastsIndexRoute,
}

const PodcastsRouteWithChildren = PodcastsRoute._addFileChildren(
  PodcastsRouteChildren,
)

interface SermonsRouteChildren {
  SermonsSlugRoute: typeof SermonsSlugRoute
  SermonsIndexRoute: typeof SermonsIndexRoute
}

const SermonsRouteChildren: SermonsRouteChildren = {
  SermonsSlugRoute: SermonsSlugRoute,
  SermonsIndexRoute: SermonsIndexRoute,
}

const SermonsRouteWithChildren =
  SermonsRoute._addFileChildren(SermonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BookAppointmentRoute: BookAppointmentRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  GiveRoute: GiveRoute,
  MediaRoute: MediaRouteWithChildren,
  PlanAVisitRoute: PlanAVisitRoute,
  PodcastsRoute: PodcastsRouteWithChildren,
  PrayerRequestRoute: PrayerRequestRoute,
  SermonsRoute: SermonsRouteWithChildren,
  ShareTestimonyRoute: ShareTestimonyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimoniesRoute: TestimoniesRoute,
  MinistriesSlugRoute: MinistriesSlugRoute,
  MinistriesMensFellowshipRoute: MinistriesMensFellowshipRoute,
  MinistriesWomensFellowshipRoute: MinistriesWomensFellowshipRoute,
  MinistriesIndexRoute: MinistriesIndexRoute,
  ApiPublicEnsureMediaBucketRoute: ApiPublicEnsureMediaBucketRoute,
  ApiPublicPingTestRoute: ApiPublicPingTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
