/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as MediaRouteImport } from './routes/media'
import { Route as GiveRouteImport } from './routes/give'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookAppointmentRouteImport } from './routes/book-appointment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinistriesWomensFellowshipRouteImport } from './routes/ministries.womens-fellowship'
import { Route as MinistriesMensFellowshipRouteImport } from './routes/ministries.mens-fellowship'
import { Route as MediaPodcastRouteImport } from './routes/media.podcast'
import { Route as MediaGalleryRouteImport } from './routes/media.gallery'
import { Route as EventsCouplesRouteImport } from './routes/events.couples'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAppointmentRoute = BookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesWomensFellowshipRoute =
  MinistriesWomensFellowshipRouteImport.update({
    id: '/ministries/womens-fellowship',
    path: '/ministries/womens-fellowship',
    getParentRoute: () => rootRouteImport,
  } as any)
const MinistriesMensFellowshipRoute =
  MinistriesMensFellowshipRouteImport.update({
    id: '/ministries/mens-fellowship',
    path: '/ministries/mens-fellowship',
    getParentRoute: () => rootRouteImport,
  } as any)
const MediaPodcastRoute = MediaPodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => MediaRoute,
} as any)
const MediaGalleryRoute = MediaGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => MediaRoute,
} as any)
const EventsCouplesRoute = EventsCouplesRouteImport.update({
  id: '/couples',
  path: '/couples',
  getParentRoute: () => EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/give': typeof GiveRoute
  '/media': typeof MediaRouteWithChildren
  '/sermons': typeof SermonsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/events/couples': typeof EventsCouplesRoute
  '/media/gallery': typeof MediaGalleryRoute
  '/media/podcast': typeof MediaPodcastRoute
  '/ministries/mens-fellowship': typeof MinistriesMensFellowshipRoute
  '/ministries/womens-fellowship': typeof MinistriesWomensFellowshipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/give': typeof GiveRoute
  '/media': typeof MediaRouteWithChildren
  '/sermons': typeof SermonsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/events/couples': typeof EventsCouplesRoute
  '/media/gallery': typeof MediaGalleryRoute
  '/media/podcast': typeof MediaPodcastRoute
  '/ministries/mens-fellowship': typeof MinistriesMensFellowshipRoute
  '/ministries/womens-fellowship': typeof MinistriesWomensFellowshipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/give': typeof GiveRoute
  '/media': typeof MediaRouteWithChildren
  '/sermons': typeof SermonsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/events/couples': typeof EventsCouplesRoute
  '/media/gallery': typeof MediaGalleryRoute
  '/media/podcast': typeof MediaPodcastRoute
  '/ministries/mens-fellowship': typeof MinistriesMensFellowshipRoute
  '/ministries/womens-fellowship': typeof MinistriesWomensFellowshipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book-appointment'
    | '/contact'
    | '/events'
    | '/give'
    | '/media'
    | '/sermons'
    | '/sitemap.xml'
    | '/events/couples'
    | '/media/gallery'
    | '/media/podcast'
    | '/ministries/mens-fellowship'
    | '/ministries/womens-fellowship'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-appointment'
    | '/contact'
    | '/events'
    | '/give'
    | '/media'
    | '/sermons'
    | '/sitemap.xml'
    | '/events/couples'
    | '/media/gallery'
    | '/media/podcast'
    | '/ministries/mens-fellowship'
    | '/ministries/womens-fellowship'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book-appointment'
    | '/contact'
    | '/events'
    | '/give'
    | '/media'
    | '/sermons'
    | '/sitemap.xml'
    | '/events/couples'
    | '/media/gallery'
    | '/media/podcast'
    | '/ministries/mens-fellowship'
    | '/ministries/womens-fellowship'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookAppointmentRoute: typeof BookAppointmentRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  GiveRoute: typeof GiveRoute
  MediaRoute: typeof MediaRouteWithChildren
  SermonsRoute: typeof SermonsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MinistriesMensFellowshipRoute: typeof MinistriesMensFellowshipRoute
  MinistriesWomensFellowshipRoute: typeof MinistriesWomensFellowshipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-appointment': {
      id: '/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof BookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries/womens-fellowship': {
      id: '/ministries/womens-fellowship'
      path: '/ministries/womens-fellowship'
      fullPath: '/ministries/womens-fellowship'
      preLoaderRoute: typeof MinistriesWomensFellowshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries/mens-fellowship': {
      id: '/ministries/mens-fellowship'
      path: '/ministries/mens-fellowship'
      fullPath: '/ministries/mens-fellowship'
      preLoaderRoute: typeof MinistriesMensFellowshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/podcast': {
      id: '/media/podcast'
      path: '/podcast'
      fullPath: '/media/podcast'
      preLoaderRoute: typeof MediaPodcastRouteImport
      parentRoute: typeof MediaRoute
    }
    '/media/gallery': {
      id: '/media/gallery'
      path: '/gallery'
      fullPath: '/media/gallery'
      preLoaderRoute: typeof MediaGalleryRouteImport
      parentRoute: typeof MediaRoute
    }
    '/events/couples': {
      id: '/events/couples'
      path: '/couples'
      fullPath: '/events/couples'
      preLoaderRoute: typeof EventsCouplesRouteImport
      parentRoute: typeof EventsRoute
    }
  }
}

interface EventsRouteChildren {
  EventsCouplesRoute: typeof EventsCouplesRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsCouplesRoute: EventsCouplesRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface MediaRouteChildren {
  MediaGalleryRoute: typeof MediaGalleryRoute
  MediaPodcastRoute: typeof MediaPodcastRoute
}

const MediaRouteChildren: MediaRouteChildren = {
  MediaGalleryRoute: MediaGalleryRoute,
  MediaPodcastRoute: MediaPodcastRoute,
}

const MediaRouteWithChildren = MediaRoute._addFileChildren(MediaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookAppointmentRoute: BookAppointmentRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  GiveRoute: GiveRoute,
  MediaRoute: MediaRouteWithChildren,
  SermonsRoute: SermonsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MinistriesMensFellowshipRoute: MinistriesMensFellowshipRoute,
  MinistriesWomensFellowshipRoute: MinistriesWomensFellowshipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
