// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uraovvxkrdvcgtwilkrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyYW92dnhrcmR2Y2d0d2lsa3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ4MjE4MzYsImV4cCI6MjEwMDM5NzgzNn0.6f1hHRIq5jicj_t02O3ngp9Kf0TjjVn78LZ7_A7GucA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});